### ISSUE TITLE
When KeyboardInterrupted, The process doesn't stop in subprocess

### ISSUE THREAD

**Issue by nabenabe0928** [automl/pynisher#12]
https://github.com/sfalkner/pynisher/issues/8
https://github.com/sfalkner/pynisher/pull/9/files
Just 4 lines, please adapt to it.

**Comment by mfeurer** [comment]
Could you please create a PR to this repository? Also, I think the bespoken PR does not set an exit status, so it probably needs to be extended.

**Comment by eddiebergman** [comment]
I tested this manually and it seems to work in the new version. Basically a keyboard interupt is automatically propogated to all subprocesses and they can manually decide what to do. There's now an option to turn this into a forceful interupt, i.e. if ctrl+c is issued, we send a sigterm to all subprocesses.

**Comment by eddiebergman** [comment]
https://github.com/automl/pynisher/blob/master/pynisher/pynisher.py#L355-L370
