### ISSUE TITLE
[doc] Wrong comments on tests

### ISSUE THREAD

**Issue by nabenabe0928** [automl/pynisher#15]
L84, 425 in [test_pynisher.py](https://github.com/automl/pynisher/blob/master/test/test_pynisher.py#L84) say `memory in MB`, but it seems that they are in `KB`.

**Comment by mfeurer** [comment]
Yes, that should be `KB`. Do you want to provide a PR to update the code?

**Comment by nabenabe0928** [comment]
Sure, I will send a PR:)

**Comment by eddiebergman** [comment]
All tests were redone, hopefully the new API makes things cleaner where you can specify the units directly
