### ISSUE TITLE
[bug] Memory limit is too tight or too loose

### ISSUE THREAD

**Issue by nabenabe0928** [automl/pynisher#16]
# Environment
- Ubuntu 18.04
- Python 3.8

# Codes to reproduce
```
import pynisher
import multiprocessing
import os
import numpy as np 


ctx = os.environ.get('CONTEXT', 'fork')


def memory_test(size_in_mb):
    dummy = np.full(1024 * 1024 * size_in_mb // 8, 42., dtype=np.float64)
    return 'OK'
```

## When the memory size is small, the constraint is too loose
```
for mem_size in [1, 50, 100]:
    func = pynisher.enforce_limits(
        mem_in_mb=1,
        context=multiprocessing.get_context(ctx))(memory_test)

    func(size_in_mb=mem_size)
    print(func.result, func.exit_status)

>>> OK 0
>>> OK 0
>>> None <class 'pynisher.limit_function_call.MemorylimitException'>
```

## When the memory size is large, the constraint is too tight
```
for mem_size in [100, 500, 1000]:
    func = pynisher.enforce_limits(
        mem_in_mb=1024,
        context=multiprocessing.get_context(ctx))(memory_test)

    func(size_in_mb=mem_size)
    print(func.result, func.exit_status)

>>> OK 0
>>> None <class 'pynisher.limit_function_call.MemorylimitException'>
>>> None <class 'pynisher.limit_function_call.MemorylimitException'>
```

# Easy solution for the tight memory consumption
Since [the current implementation](https://github.com/automl/pynisher/blob/7853548f9e4ba2702b3e7ee30246ea87beca21b9/pynisher/limit_function_call.py#L108) specifies the memory usage **including virtual set size**, we can nullify this setting by replacing it with `resource.RLIMIT_DATA`.
Then we can limit the usage of the **resident set size**.

**Comment by nabenabe0928** [comment]
Just in case, I also check the memory usage by `mprof run --include-children --interval 0.00001 python test.py` where `test.py` is:
```
import numpy as np

a = np.full(1024 * 1024 * 500 // 8, 42., dtype=np.float64)
```
Then the memory usage was:
```
MEM 1.867188 1629396316.9774
MEM 7.785156 1629396316.9839
MEM 8.457031 1629396316.9898
MEM 8.710938 1629396316.9943
MEM 10.914062 1629396317.0014
MEM 13.765625 1629396317.0085
MEM 14.574219 1629396317.0153
MEM 15.207031 1629396317.0221
MEM 16.312500 1629396317.0357
MEM 18.324219 1629396317.0549
MEM 24.199219 1629396317.0666
MEM 92.351562 1629396317.0796
MEM 238.351562 1629396317.0923
MEM 294.351562 1629396317.0982
MEM 350.351562 1629396317.1036
MEM 406.351562 1629396317.1088
MEM 464.351562 1629396317.1140
MEM 520.351562 1629396317.1189
MEM 26.660156 1629396317.1234
```
As seen in the output, the maximum memory size was 520MB and it totally does not make sense to have memory error.

**Comment by nabenabe0928** [comment]
Also, we have weird bugs in the combination of `resource` and `numpy` modules:
```
import pynisher
import resource
import numpy as np


limit_in_b = 512 * 1024 ** 2
resource.setrlimit(resource.RLIMIT_DATA, (limit_in_b, limit_in_b))


def memory_test(size_in_mb):
    size = int((1024 * 1024 * size_in_mb) // 8)
    dummy = [42.] * size
    return 'OK'


print(memory_test(400))
>>> Traceback (most recent call last):
>>>   File "free.py", line 16, in <module>
>>>     print(memory_test(400))
>>>   File "free.py", line 12, in memory_test
>>>     dummy = [42.] * size
>>> MemoryError
```
If we remove `import numpy as np`, the issue does not happen.

**Comment by mfeurer** [comment]
There are a few weird things with your example. First of all it's weird that somethings happening at all if you limit to 1MB, and also the 50MB shouldn't have worked. I sometimes have the impression that limiting to something under 100MB is kinda unreliable because of the python interpreter using memory as well. Regarding the constraint too tight, the 500MB in the 2nd example should have worked right? It probably would be best if you provide both the expected and the actual outcome.

> If we remove import numpy as np, the issue does not happen.

The pynisher limits the whole program memory usage. If you import numpy, the memory usage goes up and leaves less free memory for potential data.

> Then we can limit the usage of the resident set size.

What would be the implication of that?

**Comment by nabenabe0928** [comment]
@mfeurer 
Thanks for the clarification:)
So it should not be used for too small memory constraints then (And I believe this issue does not matter currently for most people).

About the second point, do you know how to track the usage of the whole program by python?
I was tracking the physical memory usage and `numpy` only consumes `20MB` if I understand correctly.
For example, let me run the following code:
```
import resource
import time

print(f'Start the import numpy: {time.time()}')
time.sleep(0.3)

import numpy as np

time.sleep(0.3)
print(f'Finish the import numpy: {time.time()}')
time.sleep(0.3)


diffs = [530, 520]


for size_in_mb in [3000, 2000, 1000, 600]:
    limit_in_b = size_in_mb * 1024 ** 2
    resource.setrlimit(resource.RLIMIT_DATA, (limit_in_b, limit_in_b))


    def memory_test(size_in_mb):
        size = int((1024 * 1024 * size_in_mb) // 8)
        dummy = [42.] * size
        return f'OK: {size_in_mb}MB with the limit of {limit_in_b / 1e6}MB'

    for diff in diffs:
        try:
            print(memory_test(size_in_mb - diff))
        except MemoryError:
            print(f'NG: {size_in_mb - diff}MB with the limit of {limit_in_b / 1e6}MB')
```
If I run this code by `mprof run --include-children python free.py`, I get the followings:
```
# Profiling data
MEM 0.820312 1629475613.0251
MEM 8.921875 1629475613.1327
MEM 8.921875 1629475613.2382
MEM 9.441406 1629475613.3451  <--- Start the import numpy
MEM 28.480469 1629475613.4595
MEM 28.480469 1629475613.5665
MEM 28.480469 1629475613.6742 <--- Finish the import
MEM 28.480469 1629475613.7809
MEM 28.480469 1629475613.8877
...... 

# Standard output
Start the import numpy: 1629475613.0330157
Finish the import numpy: 1629475613.7032979
OK: 2470MB with the limit of 3145.728MB
NG: 2480MB with the limit of 3145.728MB
OK: 1470MB with the limit of 2097.152MB
NG: 1480MB with the limit of 2097.152MB
OK: 470MB with the limit of 1048.576MB
NG: 480MB with the limit of 1048.576MB
OK: 70MB with the limit of 629.1456MB
NG: 80MB with the limit of 629.1456MB
```

**Comment by mfeurer** [comment]
1. That sounds interesting - do you think this would improve Auto-PyTorch and Auto-sklearn?
2. In your script python might not de-allocate used memory and you could try to see if garbage collection actually helps here.

**Comment by nabenabe0928** [comment]
For the `resource.RLIMIT_AS ---> resource.RLIMIT_DATA` issue, I think it is better to address; otherwise, we might always waste about 1GB and it happens in AutoPytorch.
Especially, when we try to use CUDA in torch, I found out that the memory constraint is even tighter. 
For example, you can try the following code with or without cuda.
```
import torch
import resource


limit_in_b = 4096 * 1024 ** 2  # 4GB
# This memory limitation is used in pynisher
resource.setrlimit(resource.RLIMIT_AS, (limit_in_b, limit_in_b))


if torch.cuda.is_available():
    print('CUDA available')
    device = torch.device('cuda')
else:
    print('Use CPU')
    device = torch.device('cpu')

# You can change 16 to an arbitrary integer
# and check if how tight the memory constraint is
dummy = torch.zeros(limit_in_b // 16).to(device)
print('OK')
```

About the second point, I will take a look at it:)

**Comment by nabenabe0928** [comment]
Memo (CUDA memory limit)
- [pytorch](https://github.com/pytorch/pytorch/blob/37c1f4a7fef115d719104e871d0cf39434aa9d56/torch/cuda/memory.py#L75-L99)
- [tensorflow](https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_memory_growth#raises)
- [keras](https://gist.github.com/raven4752/5bb381219ff87c4d9597702b3104349d)

**Comment by eddiebergman** [comment]
So I did some debugging for this in the new API changed version and can explain the variability with respect to the small memory sizes and it's behaviour.

1. The first thing is that a process will have a certain size at spawn, related to the imports it needs. [For example](https://github.com/automl/pynisher/blob/api_changes/tests/test_memory.py#L34), just running pynisher with a test used 37MB for some reason. Not sure where all it comes from but i used `psutil` to discover this. This is encapsulated in a class [`Monitor`](https://github.com/automl/pynisher/blob/api_changes/pynisher/util.py#L56) which plans to be extended and act as aground truth for size and time limits, a much needed debugging feature of Pynisher. An example of it's use is [here](https://github.com/automl/pynisher/blob/7b558af23d377c635eca98a393ae93662200d448/tests/test_memory.py#L39).
2. Next is that any size given to the process happens before limits are set. This means you can spawn a process with 5GB's and then set it's limit to 1MB and there will be no issue. The issue will only be caused once something is allocated.

Next up, `RLIMIT_AS` works as expected on Linux and does not seem to work on newer MAC OS as tested by @renesass. The python `resource.set_rlimit` seems to use underlying C functions `set_rlimit` which are described here for:
* Mac: https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/setrlimit.2.html
* Linux: https://man7.org/linux/man-pages/man2/setrlimit.2.html

Looking at it you'll find `RLIMIT_AS` is not specified for MAC but does not seem to cause a Python error as it says it [should](https://docs.python.org/3/library/resource.html#resource.setrlimit). The only two in common between Mac and Linux is `RLIMIT_RSS` and `RLIMIT_DATA`.

However the functionality enabling `Monitor`, [`psutil.memory_info`](https://psutil.readthedocs.io/en/latest/#psutil.Process.memory_info) only allows for both `rss` and `vms` (Virtual Memory Size). I think this `vms` correlates with `RLIMIT_AS` on linux and from what I gathered, there wasn't much equivalent for MAC. The good news is that allocating 20mb with `bytearray(20 * (2 ** 20))` showed that both of those memory usages (rss and vms) went up by ~20mb when this was used, meaning that for our purposes, it measure what's intended.

Given all this, we will try to implement the following:
* More testing to see the discrepancies between `rss` and `vms` memory usage by `memory_info()`
* See how all of these respond to the limits `RLIMIT_{AS,DATA,RSS}`
* Place a limit on all of these (assuming the work) to enforce more consistent behaviour.

**Comment by eddiebergman** [comment]
@nabenabe0928 I'm curious as to why we shouldn't limit `RAM + virtual` with `RLIMIT_AS` instead of just `RAM` with `RLIMIT_DATA`?

Apparently Pynisher memory constraints with GPUs existing don't play nicely, causing some kind of crash (can't test it locally). Would using `RLIMIT_DATA` work do you think and why?

We were also looking at the links you sent on limiting GPU memory which would be nice. However import tensorflow or torch, just to use the limit function is an incredibly large use of memory as you pointed out. We could work around it by having `Pynisher[tensorflow]` or `Pynisher[pytorch]` optional requirements but I imagine there's no light weight alternative.
